#Boolean operators(Having two values True and False)
print("5==5 is "+str(5==5))
print("5==6 is "+str(5==6))
print(5 is 5)
print(5 is 6)
print(5 is not 5)
print(5 is not 6)
print("This" is "This")
print("True" is "True")
print("True" is True)
print("True" is str(True))